## Introduction

좋아요 기능을 구현 하던 중 문득 떠올랐다.
유저가 좋아요 버튼을 누르면, 클라이언트로 부터 당연하게 user_id와 post_id가 들어오면서 Like 테이블에 쌓이게 될 것이다.
그런데 아예 데이터가 들어오지 않는 경우, user_id만 들어오는 경우, post_id만 들어오는 경우 등을 Back 쪽에서 에러 핸들링을 해야할까?
해야 한다면, 왜 해야할까? 팀원들과 함께 이야기를 나누면서 이유를 알 수 있었다.

## WHY

> "Postman을 통해서 접근해 온다면"?

정상적인 로직이라면, 당연히 Front End쪽에서 Back End로 정보가 전달 될 것이고, Front End 쪽에서 유효성 검사가 진행될 것이다.
그런데, Postman을 통해서 들어오는 경우는 비정상적인 접근이지만 충분히 가능한 접근이다.
그렇다면, Front End, Back End 두 쪽에서 전부 검사를 하고 경우의 수를 찾아서 에러 핸들링을 해주는 것이 맞다고 판단이 섰다.
그렇기 때문에 에러 핸들링을 훨씬 구체적으로 생각하게 되었다.

### 에러 핸들링 처리 전

```javascript
const addLike = async (req, res, next) => {
  const postId = req.params.postId;
  const userId = req.user;
  const connection = await pool.getConnection(async (conn) => conn);
  try {
    // transaction 시작
    await connection.beginTransaction();
    await connection.query(queryOfAddingPostLikes, [userId, postId]);
    await connection.query(queryOfIncreasingLikeCnt, [postId]);
    await connection.commit(); // 적용
    return res.sendStatus(201);
  } catch (err) {
    await connection.rollback(); // 에러가 발생할 경우 원래 상태로 돌리기
    return next(customizedError(err, 400));
  } finally {
    await connection.release(); // 연결 끊기
  }
};
```

### 에러 핸들링 처리 후

```javascript
const addLike = async (req, res, next) => {
  const userId = req.user;
  const postId = req.params.postId;

  /* validation check */
  try {
    await schemas.validateAsync({ userId, postId });
  } catch (err) {
    return next(customizedError(err, 400));
  }
  const connection = await pool.getConnection(async (conn) => conn);
  try {
    // transaction 시작
    await connection.beginTransaction();
    await connection.query(queryOfAddingPostLikes, [userId, postId]);
    await connection.query(queryOfIncreasingLikeCnt, [postId]);
    await connection.commit(); // 적용
    return res.sendStatus(201);
  } catch (err) {
    await connection.rollback(); // 에러가 발생할 경우 원래 상태로 돌리기
    return next(customizedError(err, 400));
  } finally {
    await connection.release(); // 연결 끊기
  }
};
```
